package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAcceptDate(java.lang.String acceptDate) {
		set("acceptDate", acceptDate);
	}

	public java.lang.String getAcceptDate() {
		return get("acceptDate");
	}

	public void setClient(java.lang.String client) {
		set("client", client);
	}

	public java.lang.String getClient() {
		return get("client");
	}

	public void setContacts(java.lang.String contacts) {
		set("contacts", contacts);
	}

	public java.lang.String getContacts() {
		return get("contacts");
	}

	public void setProjectName(java.lang.String projectName) {
		set("projectName", projectName);
	}

	public java.lang.String getProjectName() {
		return get("projectName");
	}

	public void setHmoney(java.lang.Integer hmoney) {
		set("hmoney", hmoney);
	}

	public java.lang.Integer getHmoney() {
		return get("hmoney");
	}

	public void setNmoney(java.lang.Integer nmoney) {
		set("nmoney", nmoney);
	}

	public java.lang.Integer getNmoney() {
		return get("nmoney");
	}

	public void setEstimateDate(java.lang.String estimateDate) {
		set("estimateDate", estimateDate);
	}

	public java.lang.String getEstimateDate() {
		return get("estimateDate");
	}

	public void setBusiness(java.lang.String business) {
		set("business", business);
	}

	public java.lang.String getBusiness() {
		return get("business");
	}

	public void setDesign(java.lang.String design) {
		set("design", design);
	}

	public java.lang.String getDesign() {
		return get("design");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
